### ISSUE TITLE
Corrplot Hilfe

### ISSUE THREAD

**Issue by TimonM1705** [yannick0404/GrupppenarbeitWA#11]
> Ich würde außerdem noch eine Funktion vorschlagen, welche die Daten mittels boxplots visualisiert und möglichweise eine corplot-Funktion. Was meint ihr dazu?

Ja macht Sinn. Ich hab mal den Corrplot probiert. Funktioniert auch, allerdings können nur numerische Variablen benutzt werden in einem Dataframe. Also müsste man alle Variablen erst wieder umschreiben. Ist irgendwie unschön. Habt ihr da eine bessere Idee? Außerdem macht es dann auch nur Sinn "Alter", "Interesse_mathe", "Interesse_info" und "Studienfach" zu vergleichen, wobei die Studienfächer einfach in Werte von 1 bis 4 geändert werden und man später nicht mehr erkennt, welches Fach welches ist.

_Originally posted by @TimonM1705 in https://github.com/yannick0404/GrupppenarbeitWA/issues/10#issuecomment-1043583943_

**Comment by edos1** [comment]
Man könnte ja auch MatheLk ja/nein in eine 0/1-Variable umschreiben und dann Korrelationen damit rechnen. Ich würde sagen, dass Studienfach macht tatsächlich eher weniger Sinn macht.
