### ISSUE TITLE
Fast fertig

### ISSUE THREAD

**Issue by TimonM1705** [yannick0404/GrupppenarbeitWA#12]
Hey Leute,
langsam kommen wir zum Ende. Es müssen nur noch ein paar Funktionen ausgeführt werden und im "Skript4" eingetragen werden. Vielleicht habt ihr Lust, da noch ein bisschen was zu machen. Könnt auch gerne bei den bereits angewandten Funktionen noch weitere Variablen nehmen und hinzufügen. Danach können wir im letzten Schritt die Daten auswerten und diskutieren.

**Comment by yannick0404** [comment]
Seid ihr alle fertig?

**Comment by Stammkundschaft** [comment]
Hab jetzt mal die Funktionen gemerged. An Skript4 arbeiten noch die anderen glaube ich. Da will ich nichts falschmachen.

**Comment by Stammkundschaft** [comment]
ich wäre dann aber fertig.

**Comment by TimonM1705** [comment]
Ich denke wir sind mit Skript 4 fertig. Könnten mit der Auswertung der Daten und der Diskussion beginnen. Wenn dann doch noch was fehlt, bzw. falsch ist, können wir das im Nachhinein ja nochmal verbessern.

**Comment by TimonM1705** [comment]
> Ich denke es wäre gut, wenn ihr die Auswertung schon so 95% fertig habt, bevor wir dann in die Diskussion übergehen. Sonst lohnt sich das mit der Diskussion mMn noch nicht.

Ich habe jetzt überall noch Auswertungen, bzw. Aussagen hinzugefügt. Ich hoffe mal, das ist das, was du meintest. Wenn ja, dann können wir ja diskutieren und dabei wertet man ja auch noch weiter aus.

**Comment by TobiasPytlik** [comment]
Da ich jetzt auch den letzten anderen Issue bearbeitet habe, würde ich sagen, dass wir nun zur Diskussion übergehen können nachdem wir den Branch noch in main mergen

**Comment by yannick0404** [comment]
Okey, super. Ich würde sagen dann schreiben wir mal morgen weiter.
