### ISSUE TITLE
Modalwert falsche Angabe

### ISSUE THREAD

**Issue by TobiasPytlik** [yannick0404/GrupppenarbeitWA#13]
Die Modalwertberechnung aus b ist fehlerhaft, dort wird denke ich angegeben wie oft der am häufigsten auftretende Wert tatsächlich auftritt, aber nicht welcher Wert das ist, was für die Analyse viel interessanter wäre.

**Comment by TobiasPytlik** [comment]
Ok habe das direkt gelöst, gerne trotzdem nochmal drüber schauen

**Comment by TimonM1705** [comment]
> Ok habe das direkt gelöst, gerne trotzdem nochmal drüber schauen

Ja das hatte ich auch bemerkt, kam gerade aber nicht drauf, wie man das ändert. Danke, sieht gut aus
