### ISSUE TITLE
Beginn mit 3. Aufgabenteil

### ISSUE THREAD

**Issue by yannick0404** [yannick0404/GrupppenarbeitWA#2]
Guten Abend,
@edos1  und ich haben den Datensatz nun erstellt. Wenn ihr alle breit seid, können wir jetzt mit dem Erstellen der Funktionen beginnen.
Es wäre gut wenn ihr einmal alle antworten könntet!

**Comment by TimonM1705** [comment]
> Guten Abend,
> @edos1 und ich haben den Datensatz nun erstellt. Wenn ihr alle breit seid, können wir jetzt mit dem Erstellen der Funktionen beginnen.
> Es wäre gut wenn ihr einmal alle antworten könntet!

Alles klar. Vielen Dank und gute Arbeit

**Comment by edos1** [comment]
Sehr gerne.

**Comment by TobiasPytlik** [comment]
Super, ich bin bereit
