### ISSUE TITLE
Modalwert des Studiengangs

### ISSUE THREAD

**Issue by TimonM1705** [yannick0404/GrupppenarbeitWA#26]
Die Funktion b) gibt aus, dass der Modalwert des Studiengangs das Fach Mathematik ist, dabei sollte eigentlich das Fach Data Science ausgeben werden. Dies gibt auch der Barplot in f) aus. Hab das auch im Datensatz abgeglichen.

**Comment by TobiasPytlik** [comment]
Jo vielen Dank für die Info. Habe ich direkt angepasst
