### ISSUE TITLE
Csv Datei fehlerhaft

### ISSUE THREAD

**Issue by TobiasPytlik** [yannick0404/GrupppenarbeitWA#6]
Habe gerade mal kurz in die csv-Datei geschaut und mir ist aufgefallen, dass zwischen Alter und Studienfach eine merkwürdige Zahl steht, glaube die gehört da nicht hin @yannick0404 @edos1

**Comment by yannick0404** [comment]
Danke für den Hinweis, wir kümmern uns drum!

**Comment by edos1** [comment]
Ist ja jetzt geklärt, dann schließe ich das hier mal
