### ISSUE TITLE
Verschiedene Branches

### ISSUE THREAD

**Issue by edos1** [yannick0404/GrupppenarbeitWA#7]
Funktionen1 und funktionen2 in zwei verschiedene Branches zu packen, sorgt mMn nur dafür, dass die beiden am Ende nicht mehr zusammenpassen  (Aufgabenteil e gibt es ja jetzt auch schon zweimal #5 ). Deshalb sollte wir die beiden zumindest mergen oder eigentlich noch besser einfach im main arbeiten. Falls ihr keine guten Gründe dagegen habt würde ich dann so machen.

**Comment by yannick0404** [comment]
Jap, ich sehe deinen Punkt und erachte ich eine Zusammenführung der beiden Branches als sinnvoll. 
Die Branches komplett in main zu bearbeiten, finde ich jedoch schwierig, da ich besonders den Vorteil der Kommentare in einem Pull-Request sehe. So können einzelne "Abgaben" zitiert und verbessert werden ohne sich in verschiedene Aufgabenteilen in die Quere zu kommen.

**Comment by edos1** [comment]
Ja von mir aus auch gerne in einem Branch, der nicht der Main ist. Hauptsache in einem.

**Comment by Stammkundschaft** [comment]
Dachte, dass Funktionen2 aus Funktionen für das R-Skript 2 besteht. Aber wenn dies gar nicht der Fall ist, wäre es wirklich sinnvoller nur ein Branch zu machen, indem wir die komplette Aufgabe 3 in einem Branch und die Aufgabe 4 in einem anderen Branch (habe ich schon erstellt) machen.
