### ISSUE TITLE
Aufgabenteil 2 fertig

### ISSUE THREAD

**Issue by TimonM1705** [yannick0404/GrupppenarbeitWA#8]
Ich habe die letzte Funktion geschrieben. Ich hab die Funktion jedoch noch nicht getestet. Vielleicht könntet ihr da mal bei gegebener Zeit drüber schauen. Außerdem habe ich probiert eine Hilfsfunktion dafür zu erstellen und diese in "Funktionen2" hochgeladen.
Wenn das alles passt, dann können wir jetzt im nächsten Schritt mit der Visualisierung der Daten anfangen.

**Comment by edos1** [comment]
Sieht alles gut aus. Mehr geht natürlich immer, aber ich denke der Umfang so ist ganz anständig.
