### ISSUE TITLE
Probleme beim einlesen der csv Datei

### ISSUE THREAD

**Issue by TobiasPytlik** [yannick0404/GrupppenarbeitWA#9]
Habe gerade schon mit Aufgabe 4 begonnen, der Datensatz ließ sich eigentlich recht gut einlesen, allerding kommt es zu Komplikationen bei der Abfrage nach einem factor. Keine der Variablen ist ein factor, weshalb ich zum Beipiel für die Funktion aus b mit keine Spalte arbeiten kann. Soll ich mir die entsprechenden Variablen dann einfach als factor umschreiben?

**Comment by TimonM1705** [comment]
Ja, ich habe einfach die Variablen umgeändert zu "factor". Ich habe das auch in dem Skript4 hinzugefügt.
Außerdem hab ich ein bisschen was für die Visualisierung gemacht und dafür ein PDF hochgeladen. Leider ohne Überschriften und ohne geeignete Maße. Somit kann man man nicht wirklich erkennen, was gezeigt werden soll. Möglicherweise habt ihr da eine Idee für.
